[witsummon]
enabled=0
[bot]
nick=Wit
password=
server=localhost
remoteport=6667
bindaddress=127.0.0.1
channels=#test
persist=true
IDNetwork=2
autoplayconfig=autoplay1

[autoplay1]
#test=trivial,5
#test2=trivial,5
